name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: |
          # Создаем файлы окружения, если их нет
          echo "rootProject.name = 'minimap'" > settings.gradle
          gradle wrapper --gradle-version 8.10
          chmod +x gradlew
          # Сборка мода
          ./gradlew build --no-daemon

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Minimap-Jar
          path: build/libs/*.jar
